# Hit ArchLens 기본 설정 파일

# 데이터 설정
data:
  icons_dir: "aws_cv_clip/icons"  # 실제 아이콘 디렉터리 경로로 수정
  taxonomy_csv: "aws_cv_clip/aws_resources_models.csv"  # 실제 택소노미 파일 경로로 수정
  images_dir: "images"
  output_dir: "out"  # 모든 결과물을 out/에 저장

# Computer Vision 설정
cv:
  clip_name: "ViT-B-32"
  clip_pretrained: "laion2b_s34b_b79k"
  device: "auto"  # "cuda", "cpu", "auto"

# Large Language Model 설정
llm:
  provider: "openai"  # "openai", "deepseek", "anthropic", "local"
  base_url: "https://api.openai.com/v1"
  api_key: "${OPENAI_API_KEY}"  # 환경변수에서 로드
  vision_model: "gpt-4o"
  timeout: 120
  max_retries: 3

# 객체 감지 설정
detection:
  max_size: 1600
  canny_low: 60
  canny_high: 160
  mser_delta: 5
  min_area: 900
  max_area: 90000
  win: 128
  stride: 96
  iou_nms: 0.45
  use_canny: true
  use_mser: true
  use_sliding_window: true

# 검색 및 매칭 설정
retrieval:
  topk: 5
  accept_score: 0.35
  orb_nfeatures: 500
  score_clip_w: 0.7
  score_orb_w: 0.3
  score_ocr_w: 0.1

# 런타임 설정
runtime:
  mode: "full_image"  # "full_image", "patch", "hybrid"
  conf_threshold: 0.5
  patch_size: 512
  patch_stride: 256
  max_tokens: 2000
  temperature: 0.0
  batch_size: 1

# 하이브리드 융합 설정
hybrid:
  cv_weight: 0.6
  llm_weight: 0.4
  fusion_method: "weighted"  # "weighted", "ensemble", "confidence", "iou_based"
  iou_threshold: 0.5
  confidence_threshold: 0.3

# OCR 설정
ocr:
  enabled: true
  lang: ["en"]
  confidence_threshold: 0.5

# 데이터 수집 설정
collectors:
  icons:
    zip_path: "./Asset-Package.zip"  # 프로젝트 루트 기준 상대 경로
    output_dir: "out/aws/icons"
  services:
    output_dir: "out/aws/services"
  products:
    api_url: "https://aws.amazon.com/api/dirs/items/search?item.directoryId=aws-products&sort_by=item.additionalFields.productNameLowercase&size=1000&language=en&item.locale=en_US"
    output_dir: "out/aws/products"
    timeout: 30

# AWS 설정
aws:
  region: "us-east-1"
  max_retries: 3
  timeout: 30

# 로깅 설정
logging:
  level: "INFO"  # "DEBUG", "INFO", "WARNING", "ERROR"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/hit_archlens.log"

# 성능 설정
performance:
  parallel_processing: true
  max_workers: 4
  memory_limit: "4GB"
  cache_enabled: true
  cache_dir: "cache"
