# Ultra Performance Configuration
# 극적인 성능 개선을 위한 설정

performance:
  # 모델 양자화 설정
  use_quantization: true
  quantization_type: "int8"  # int8, fp16, dynamic
  
  # 배치 처리 설정
  use_batch_processing: true
  batch_size: 32
  max_batch_queue_size: 100
  
  # 캐싱 설정
  use_caching: true
  cache_size: 2000
  cache_ttl: 3600  # 1시간
  cache_persistence: true
  
  # 멀티스레딩 설정
  use_multithreading: true
  num_threads: 8
  thread_pool_size: 16
  
  # GPU 가속 설정
  use_gpu: true
  gpu_memory_fraction: 0.8
  mixed_precision: true
  
  # 메모리 최적화
  memory_optimization: true
  gradient_checkpointing: true
  memory_efficient_attention: true
  
  # 하드웨어 가속
  use_tensorrt: true
  use_openvino: false
  use_onnx: true

cv:
  # CLIP 모델 설정
  clip_name: "openai/clip-vit-base-patch32"
  clip_quantized: true
  
  # 특징 추출기 설정
  feature_extractor: "efficientnet-b0"
  feature_dim: 512
  
  # 감지 설정
  detection_method: "hybrid"  # sliding_window, selective_search, edge_based
  min_confidence: 0.3
  max_detections: 100
  
  # 이미지 전처리
  input_size: [224, 224]
  normalize: true
  augment: false

llm:
  # LLM 설정
  model_name: "gpt-4"
  max_tokens: 512
  temperature: 0.1
  
  # 배치 처리
  batch_size: 4
  concurrent_requests: 8

hybrid:
  # 융합 설정
  cv_weight: 0.7
  llm_weight: 0.3
  fusion_method: "weighted_confidence"
  iou_threshold: 0.5
  confidence_threshold: 0.4
  
  # 후처리
  nms_threshold: 0.3
  max_per_class: 10

optimization:
  # 컴파일러 최적화
  use_torch_compile: true
  use_jit: true
  use_torchscript: true
  
  # 커널 최적화
  use_cudnn: true
  use_mkldnn: true
  
  # 메모리 풀
  use_memory_pool: true
  pool_size: 1024

monitoring:
  # 성능 모니터링
  enable_profiling: true
  profile_memory: true
  profile_time: true
  
  # 메트릭 수집
  collect_metrics: true
  metrics_interval: 60

caching:
  # 캐시 설정
  backend: "redis"  # memory, redis, disk
  redis_url: "redis://localhost:6379"
  
  # 캐시 키 설정
  key_prefix: "archlens"
  key_ttl: 3600

# 하드웨어별 최적화 설정
hardware_profiles:
  high_end_gpu:
    use_quantization: true
    batch_size: 64
    num_threads: 16
    use_tensorrt: true
    
  mid_range_gpu:
    use_quantization: true
    batch_size: 32
    num_threads: 8
    use_tensorrt: false
    
  cpu_only:
    use_quantization: false
    batch_size: 16
    num_threads: 4
    use_multithreading: true
